name: Build Windows x86_64

on: 
  push: 
    branches: [ "main" ]

jobs:
  build-windows-x86_64:
    runs-on: windows-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up MSYS2 (MINGW64)
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          install: >-
            mingw-w64-x86_64-gcc
            mingw-w64-x86_64-pkg-config

      - name: Build (x86_64)
        shell: msys2 {0}
        run: |
          gcc main.cpp -O2 -std=c11 -mwindows -static -I. \
            -ladvapi32 -lole32 -lshell32 -lshlwapi -luser32 -lversion \
            -o webview.exe

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: webview
          path: webview.exe
