name: Build Windows (x64 & ARM64)

on: 
  push: 
    branches: [ "main" ]

jobs:
  build-windows:
    runs-on: windows-latest
    strategy:
      matrix:
        arch: [x64, arm64]

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up MinGW for ${{ matrix.arch }}
        uses: egor-tensin/setup-mingw@v2
        with:
          platform: ${{ matrix.arch }}

      - name: Build for ${{ matrix.arch }}
        shell: bash
        run: |
          gcc main.c -O2 -std=c11 -mwindows -static -I. \
            -ladvapi32 -lole32 -lshell32 -lshlwapi -luser32 -lversion \
            -o app-${{ matrix.arch }}.exe

      - name: Upload artifact (${{ matrix.arch }})
        uses: actions/upload-artifact@v4
        with:
          name: app-windows-${{ matrix.arch }}
          path: app-${{ matrix.arch }}.exe
