name: Linux x86_64

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y g++ pkg-config libgtk-3-dev libwebkit2gtk-4.1-dev

      - name: Build
        run: g++ main.cpp -O2 -std=c++14 -I. $(pkg-config --cflags --libs gtk+-3.0 webkit2gtk-4.1) -o webview

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: webview
          path: webview
